<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerISO1tC4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerISO1tC4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerISO1tC4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerISO1tC4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerISO1tC4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ISO1tC4',
    'container.build_id' => 'c752da03',
    'container.build_time' => 1531312659,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerISO1tC4');
