#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: index.html.twig

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
